### ISSUE TITLE
pdfreactor is amd64 only

### ISSUE THREAD

**Issue by rfay** [drud/ddev-pdfreactor#2]
I note that https://hub.docker.com/r/realobjects/pdfreactor/tags has no arm64 images pushed, which means it's unlikely to work properly on mac M1 machines or other arm64 machines. 

It's important to contact them and ask that they start to push both architectures.

At the least the README here needs to mention the incompatibility.

**Comment by blankse** [comment]
@rfay I contacted the PDFreactor support. They plan to support this with the release of the next major version of PDFreactor (PDFreactor 12) and have reported it as a feature in their internal tracking system.

I add this note to the readme: #4
Is this OK for you?

**Comment by blankse** [comment]
@rfay Thanks for your input and review
