### ISSUE TITLE
Proposal: Remove from "officially" supported status Jan 1, 2025

### ISSUE THREAD

**Issue by rfay** [drud/ddev-pdfreactor#22]
This add-on has extremely low usage, 9-16 reported usages per month. It should be moved to non-official status. It can move to @blankse maybe? Are you interested? Or we can move it to `rfay` org. 

If we don't hear anything we'll move this somewhere unofficial after Jan 1, 2025.

**Comment by blankse** [comment]
@rfay We can then move it back to me.

**Comment by rfay** [comment]
Works for me, thanks. I guess you don't have a fork as I see it redirecting from https://github.com/blankse/ddev-pdfreactor. 

Since you're probably the key user, I think it would be good to be in your space. 

I invited you to https://github.com/ddevl, once you're in there I can transfer this to ddevl, and you can then transfer to blankse. (I tried directly transferring to blankse, but they still don't allow that.)

**Comment by blankse** [comment]
@rfay I have accepted your invitation.

**Comment by rfay** [comment]
OK, done. I'll want to use a different org next time we do one of these, since this already had a backup fork there! 

You should be able to transfer it to blankse or to an org of your choice now. Thanks!

**Comment by blankse** [comment]
@rfay I have transferred it.

**Comment by rfay** [comment]
Thanks!

**Comment by stasadev** [comment]
And this add-on needs a new release with this replacement:

```diff
-ddev/ddev-pdfreactor
+blankse/ddev-pdfreactor
```

Thank you.

**Comment by rfay** [comment]
Thanks so much for maintaining this @blankse !

**Comment by blankse** [comment]
@stasadev Done: https://github.com/blankse/ddev-pdfreactor/releases/tag/v1.0.7

**Comment by stasadev** [comment]
@blankse, please disable/enable the GitHub workflow to make yourself an owner.

![Image](https://github.com/user-attachments/assets/be2782ab-a1eb-4960-9d52-a130a485e7f4)

It's triggered by `ddevactions`, which means we receive all notifications about failed tests, not you.

https://github.com/blankse/ddev-pdfreactor/actions/workflows/tests.yml

![Image](https://github.com/user-attachments/assets/69b67ac7-d16a-4440-894a-5f0bb30e2363)

**Comment by blankse** [comment]
@stasadev I disabled/enabled the GitHub workflow "tests".
