### ISSUE TITLE
tests failing: "[pimcore] Symfony\Component\HttpFoundation\Exception\SessionNotFoundException: There is currently no session available. in RequestStack.php:126"

### ISSUE THREAD

**Issue by rfay** [drud/ddev-pdfreactor#8]
@blankse tests are failing completely the last few nights with 

> [pimcore] Symfony\Component\HttpFoundation\Exception\SessionNotFoundException: There is currently no session available. in RequestStack.php:126"

Could you please take a look at this and get it sorted?

**Comment by blankse** [comment]
@rfay It seems the new Pimcore Version has a bug. I try to create a test without Pimcore.

**Comment by blankse** [comment]
@rfay I created a PR https://github.com/drud/ddev-pdfreactor/pull/9

**Comment by rfay** [comment]
Thanks!
